### ISSUE TITLE
[Feature] Duplicate File Recovery

### ISSUE THREAD

**Issue by sv410** [Kota-Karthik/twinTrim#105]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem you're trying to solve.

This feature will allow users to recover files that were accidentally deleted during the duplicate removal process. It will maintain a backup of deleted files in a designated recovery directory for a specified period before permanently deleting them.
**Describe the solution you'd like**
This feature will allow users to recover files that were accidentally deleted during the duplicate removal process. It will maintain a backup of deleted files in a designated recovery directory for a specified period before permanently deleting them.

**Describe alternatives you've considered**
Version Control System Integration
Description: Integrate with a version control system like Git to manage file versions and recover deleted files.

Pros: Offers a robust version history and rollback capabilities. Supports collaborative environments.

Cons: May introduce complexity in setting up and managing Git repositories for users unfamiliar with version control.

**Additional context**

**Comment by techy4shri** [comment]
Let's break down all the issues with this issue, shall we?
1. Always check whether someone else has raised a similar issue before, you issue here clearly ignored that.
2. Always follow proper issue template while raising one in order to make it clear and give it weight. You did not.
3. Always check and READ the README.md (notice the caps please). It tells you what the project need and what not.
4. The features proposed here are not suited for a pyton package whose aim is to simply do one task through CLI.
5. You have worked in previous issues before so I am going to issue a warning here too: do not try to farm points here or you'll be liable to face consequences including but not limited to future ban and report with full ban from the program itself. Consider yourself warned.

So the conclusion we reach is this, due to your issue not being plausible and ignoring the norms of the program and the repository in general, we will be closing this and consider this a warning. If you raise issues without
